Views/Controllers/CidadeController.cs
using Model;
using Newtonsoft.Json;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Views.Controllers
{
    public class CidadeController : Controller
    {
        private CidadeRepository repository;

        public CidadeController()
        {
            repository = new CidadeRepository();
        }

        public ActionResult Index()
        {
            List<Cidade> cidades = repository.ObterTodos("");
            ViewBag.Cidades = cidades;
            return View();
        }

        public ActionResult ObterTodos(string busca)
        {
            List<Cidade> cidades = repository.ObterTodos(busca);
            string jsonResult = JsonConvert.SerializeObject(cidades, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Content(jsonResult, "application/json");
        }

        public ActionResult Cadastro()
        {
            EstadoRepository estadoRepository = new EstadoRepository();
            List<Estado> estados = estadoRepository.ObterTodos("");
            ViewBag.Estados = estados;
            return View();
        }

        public ActionResult Store(int idEstado, string nome, string numeroHabitantes)
        {
            Cidade cidade = new Cidade();
            cidade.IdEstado = idEstado;
            cidade.Nome = nome;
            cidade.NumeroHabitantes = numeroHabitantes;
            repository.Inserir(cidade);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Cidade cidade = repository.ObterPeloId(id);
            ViewBag.Cidade = cidade;

            EstadoRepository estadoRepository = new EstadoRepository();
            List<Estado> estados = estadoRepository.ObterTodos("");
            ViewBag.Estados = estados;
            return View();
        }

        public ActionResult Update(int idEstado, string nome, string numeroHabitantes, int id)
        {
            Cidade cidade = new Cidade();
            cidade.Id = id;
            cidade.IdEstado = idEstado;
            cidade.Nome = nome;
            cidade.NumeroHabitantes = numeroHabitantes;
            repository.Alterar(cidade);
            return RedirectToAction("Index");
        }
    }
}

Views/Views/Cidade/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<div class="container">
    <div class="card card-register mx-auto mt-4">
        <div class="card-header">Registro de Cidade</div>
        <div class="card-body">
            <form action="@Url.Action("Store")" method="post">
                <div class="form-group">
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-label-group">
                                    <label for="campo-estado">Estado</label>
                                    <select id="campo-estado" name="idEstado" class="form-control" required="required">
                                        <option disabled="disabled" selected="selected" value="">Selecione o Estado</option>
                                        @foreach (Model.Estado estado in ViewBag.Estados)
                                        {
                                            <option value="@estado.Id">@estado.Nome</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-12 ">
                                <div class="form-label-group">
                                    <label for="campo-cidade">Cidade</label>
                                    <input type="text" id="campo-cidade" class="form-control" placeholder="Nome da Cidade" required="required" autofocus="autofocus" name="nome" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-12 ">
                                <div class="form-label-group">
                                    <label for="campo-numero-habitantes-">Numero de Habitantes</label>
                                    <input type="text" id="campo-numero-habitantes" class="form-control" placeholder="Número de Habitantes" required="required" autofocus="autofocus" name="numeroHabitantes">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success col-md-12" type="submit">Registrar</button>
            </form>
            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Index", "Cidade")">Deseja alterar alguma cidade ja cadastrada ?</a>
            </div>
        </div>
    </div>
</div>

Views/Views/Cidade/Editar.cshtml
@{
    ViewBag.Title = "Editar";
}
<div class="container">
    <div class="card card-register mx-auto mt-4">
        <div class="card-header">Editar Cidade</div>
        <div class="card-body">
            <form action="@Url.Action("Update")" method="post">
                <input type="hidden" name="id" value="@ViewBag.Cidade.Id" />
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-label-group">
                                <label for="id">Código</label>
                                <input type="text" id="id" name="id" class="form-control"
                                       placeholder="Código" required="required"
                                       value="@ViewBag.Cidade.Id" readonly="readonly" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-label-group">
                                <label for="campo-estado">Estado</label>
                                <select id="campo-estado" name="idEstado" class="form-control" required="required">
                                    @foreach (Model.Estado estado in ViewBag.Estados)
                                    {
                                        if (estado.Id == ViewBag.Cidade.IdEstado)
                                        {
                                            <option value="@estado.Id" selected="selected">@estado.Nome</option>
                                        }
                                        else
                                        {
                                            <option value="@estado.Id">@estado.Nome</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-label-group">
                                <label for="campo-cidade">Cidade</label>
                                <input type="text" id="campo-cidade" class="form-control" placeholder="Nome" required="required" autofocus="autofocus" name="nome" value="@ViewBag.Cidade.Nome">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-12 ">
                            <div class="form-label-group">
                                <label for="campo-numero-habitantes">Numero de Habitantes</label>
                                <input type="text" id="campo-numero-habitantes" class="form-control" placeholder="Número de Habitantes" required="required" autofocus="autofocus" name="numeroHabitantes" value="@ViewBag.Cidade.NumeroHabitantes">
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success col-md-12" type="submit">Salvar</button>
            </form>
            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Index", "Cidade")">Deseja alterar alguma Cidade já registrado ?</a>
            </div>
        </div>
    </div>
</div>

Views/Views/Cidade/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Lista de Cidades</h2>
<div>
    <a href="@Url.Action("Cadastro")" class="btn btn-primary mt-1">Nova Cidade</a>
</div>
<div class="row">
    <div class="col-3 offset-9">
        <div class="form-group">
            <input type="text" id="campo-pesquisa" placeholder="Busca" class="form-control" />
        </div>
    </div>
</div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Código</th>
            <th>Estado</th>
            <th>Nome</th>
            <th>Número de Habitantes</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody id="lista-cidades"></tbody>
    <tfoot>
        <tr>
            <th>Código</th>
            <th>Estado</th>
            <th>Nome</th>
            <th>Número de Habitantes</th>
            <th>Ação</th>
        </tr>
    </tfoot>
</table>
<script src="~/Scripts/Cidade/Cidade.js"></script>