Views/Controllers/ProjetoController.cs
using Model;
using Newtonsoft.Json;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Views.Controllers
{
    public class ProjetoController : Controller
    {
        private ProjetoRepository repository;

        public ProjetoController()
        {
            repository = new ProjetoRepository();
        }

        // GET: Projeto
        public ActionResult Index()
        {
            List<Projeto> projetos = repository.ObterTodos("");
            ViewBag.Projetos = projetos;
            return View();
        }

        public ActionResult ObterTodos(string busca)
        {
            List<Projeto> projetos = repository.ObterTodos(busca);
            string jsonResult = JsonConvert.SerializeObject(projetos, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Content(jsonResult, "application/json");
        }

        public ActionResult Cadastro()
        {
            ClienteRepository clienteRepository = new ClienteRepository();
            List<Cliente> clientes = clienteRepository.ObterTodos("");
            ViewBag.Clientes = clientes;
            return View();
        }

        public ActionResult Store(int idCliente, string nome, DateTime dataCriacaoProjeto, DateTime dataFinalizacao)
        {
            Projeto projeto = new Projeto();
            projeto.IdCliente = idCliente;
            projeto.Nome = nome;
            projeto.DataCriacaoProjeto = dataCriacaoProjeto;
            projeto.DataFinalizacao = dataFinalizacao;
            repository.Inserir(projeto);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Projeto projeto = repository.ObterPeloId(id);
            ViewBag.Projeto = projeto;

            ClienteRepository clienteRepository = new ClienteRepository();
            List<Cliente> clientes = clienteRepository.ObterTodos("");
            ViewBag.Clientes = clientes;
            return View();
        }

        public ActionResult Update(int idCliente, string nome, DateTime dataCriacaoProjeto, DateTime dataFinalizacao, int id)
        {
            Projeto projeto = new Projeto();
            projeto.Id = id;
            projeto.IdCliente = idCliente;
            projeto.Nome = nome;
            projeto.DataCriacaoProjeto = dataCriacaoProjeto;
            projeto.DataFinalizacao = dataFinalizacao;
            repository.Alterar(projeto);
            return RedirectToAction("Index");
        }
    }
}

Views/Views/Projeto/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<div class="container">
    <div class="card card-register mx-auto mt-4">
        <div class="card-header">Registro de Projeto</div>
        <div class="card-body">
            <form action="@Url.Action("Store")" method="post">
                <div class="form-group">
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-cliente">Cliente</label>
                                    <select id="campo-cliente" name="idCliente" class="form-control" required="required">
                                        <option disabled="disabled" selected="selected">Selecione um Cliente</option>
                                        @foreach (Model.Cliente cliente in ViewBag.Clientes)
                                        {
                                            <option value="@cliente.Id">@cliente.Nome</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-nome">Nome</label>
                                    <input type="text" id="campo-nome" class="form-control" required="required"
                                           placeholder="Nome do Projeto" autofocus="autofocus" name="nome" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-data-criacao">Data Criação</label>
                                    <input type="datetime" id="campo-data-criacao" class="form-control data" placeholder="Data de Criação" required="required"
                                           autofocus="autofocus" name="dataCriacaoProjeto" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-data-finalizacao">Data Finalização</label>
                                    <input type="datetime" id="campo-data-finalizacao" class="form-control data" placeholder="Data de Finalização" required="required"
                                           autofocus="autofocus" name="dataFinalizacao" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success col-md-12" type="submit">Registrar</button>
            </form>
            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Index", "Projeto")">Deseja alterar algum projeto já cadastrad ?</a>
            </div>
        </div>
    </div>
</div>

Views/Views/Projeto/Editar.cshtml
@{
    ViewBag.Title = "Editar";
}

<div class="container">
    <div class="card card-register mx-auto mt-4">
        <div class="card-header">Editar Projeto</div>
        <div class="card-body">
            <form action="@Url.Action("Update")" method="post">
                <input type="hidden" name="id" value="@ViewBag.projeto.Id" />
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-label-group">
                                <label for="id">Código</label>
                                <input type="text" id="id" name="id" class="form-control"
                                       placeholder="Código" required="required"
                                       value="@ViewBag.Projeto.Id" readonly="readonly" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-cliente">Cliente</label>
                                    <select id="campo-cliente" name="idCliente" class="form-control" required="required">
                                        @foreach (Model.Cliente cliente in ViewBag.Clientes)
                                        {
                                            if (cliente.Id == ViewBag.Projeto.IdCliente)
                                            {
                                                <option value="@cliente.Id" selected="selected">@cliente.Nome</option>
                                            }
                                            else
                                            {
                                                <option value="@cliente.Id">@cliente.Nome</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-nome">Nome</label>
                                    <input type="text" id="campo-nome" class="form-control" required="required"
                                           placeholder="Nome" autofocus="autofocus" name="nome" value="@ViewBag.Projeto.Nome" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-data-criacao">Data Criação</label>
                                    <input type="datetime" id="campo-data-criacao" class="form-control data" required="required"
                                           autofocus="autofocus" name="dataCriacaoProjeto" value="@ViewBag.Projeto.DataCriacaoProjeto.ToString("dd-MM-yyyy")" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-data-finalizacao">Data Finalização</label>
                                    <input type="datetime" id="campo-data-finalizacao" class="form-control data" required="required"
                                           autofocus="autofocus" name="dataFinalizacao" value="@ViewBag.Projeto.DataFinalizacao.ToString("dd-MM-yyyy")" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success col-md-12" type="submit">Salvar</button>
            </form>
            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Index", "Projeto")">Deseja alterar algum projeto já registrado ?</a>
            </div>
        </div>
    </div>
</div>

Views/Views/Projeto/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Lista de Projetos</h2>
<div>
    <a href="@Url.Action("Cadastro")" class="btn btn-primary mt-1">Novo Projeto</a>
</div>
<div class="row">
    <div class="col-3 offset-9">
        <div class="form-group">
            <input type="text" id="campo-pesquisa" placeholder="Busca" class="form-control" />
        </div>
    </div>
</div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Código</th>
            <th>Cliente</th>
            <th>Nome Projeto</th>
            <th>Data de Criação</th>
            <th>Data de Finalização</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody id="lista-projetos"></tbody>
    <tfoot>
        <tr>
            <th>Código</th>
            <th>Cliente</th>
            <th>Nome Projeto</th>
            <th>Data de Criação</th>
            <th>Data de Finalização</th>
            <th>Ação</th>
        </tr>
    </tfoot>
</table>
<script src="~/Scripts/Projeto/Projeto.js"></script>