Views/Controllers/TarefaController.cs
using Model;
using Newtonsoft.Json;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Views.Controllers
{
    public class TarefaController : Controller
    {
        private TarefaRepository repository;

        public TarefaController()
        {
            repository = new TarefaRepository();
        }

        public ActionResult Index()
        {
            List<Tarefa> tarefas = repository.ObterTodos("");
            ViewBag.Tarefas = tarefas;
            return View();
        }

        public ActionResult ObterTodos(string busca)
        {
            List<Tarefa> tarefas = repository.ObterTodos(busca);
            string jsonResult = JsonConvert.SerializeObject(tarefas, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Content(jsonResult, "application/json");
        }

        public ActionResult Cadastro()
        {
            ProjetoRepository projetoRepository = new ProjetoRepository();
            List<Projeto> projetos = projetoRepository.ObterTodos("");
            ViewBag.Projetos = projetos;

            UsuarioRepository usuarioRepository = new UsuarioRepository();
            List<Usuario> usuarios = usuarioRepository.ObterTodos("");
            ViewBag.Usuarios = usuarios;

            CategoriaRepository categoriaRepository = new CategoriaRepository();
            List<Categoria> categorias = categoriaRepository.ObterTodos("");
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Store(int idUsuarioResponsavel, int idProjeto, int idCategoria, string titulo, string descricao, DateTime duracao)
        {
            Tarefa tarefa = new Tarefa();
            tarefa.IdUsuarioResponsavel = idUsuarioResponsavel;
            tarefa.IdProjeto = idProjeto;
            tarefa.IdCategoria = idCategoria;
            tarefa.Titulo = titulo;
            tarefa.Descricao = descricao;
            tarefa.Duracao = duracao;
            repository.Inserir(tarefa);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Tarefa tarefa = repository.ObterPeloId(id);
            ViewBag.Tarefa = tarefa;

            ProjetoRepository projetoRepository = new ProjetoRepository();
            List<Projeto> projetos = projetoRepository.ObterTodos("");
            ViewBag.Projetos = projetos;

            UsuarioRepository usuarioRepository = new UsuarioRepository();
            List<Usuario> usuarios = usuarioRepository.ObterTodos("");
            ViewBag.Usuarios = usuarios;

            CategoriaRepository categoriaRepository = new CategoriaRepository();
            List<Categoria> categorias = categoriaRepository.ObterTodos("");
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Update(int id, int idUsuarioResponsavel, int idProjeto, int idCategoria, string titulo, string descricao, DateTime duracao)
        {
            Tarefa tarefa = new Tarefa();
            tarefa.Id = id;
            tarefa.IdUsuarioResponsavel = idUsuarioResponsavel;
            tarefa.IdProjeto = idProjeto;
            tarefa.IdCategoria = idCategoria;
            tarefa.Titulo = titulo;
            tarefa.Descricao = descricao;
            tarefa.Duracao = duracao;
            repository.Alterar(tarefa);
            return RedirectToAction("Index");
        }
    }
}

Views/Views/Tarefa/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<div class="container">
    <div class="card card-register mx-auto mt-4">
        <div class="card-header">Registro de Tarefa</div>
        <div class="card-body">
            <form action="@Url.Action("Store")" method="post">
                <div class="form-group">
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-usuario">Usuario</label>
                                    <select id="campo-usuario" name="idUsuarioResponsavel" class="form-control" required="required">
                                        <option disabled="disabled" selected="selected">Selecione o Usuário Responsável</option>
                                        @foreach (Model.Usuario usuario in ViewBag.Usuarios)
                                        {
                                            <option value="@usuario.Id">@usuario.Nome</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-projeto">Projeto</label>
                                    <select id="campo-projeto" name="idProjeto" class="form-control" required="required">
                                        <option disabled="disabled" selected="selected">Selecione um Projeto</option>
                                        @foreach (Model.Projeto projeto in ViewBag.Projetos)
                                        {
                                            <option value="@projeto.Id">@projeto.Nome</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-categoria">Categoria</label>
                                    <select id="campo-categoria" name="idCategoria" class="form-control" required="required">
                                        <option disabled="disabled" selected="selected">Selecione uma Categoria</option>
                                        @foreach (Model.Categoria categoria in ViewBag.Categorias)
                                        {
                                            <option value="@categoria.Id">@categoria.Nome</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-titulo">Título</label>
                                    <input type="text" id="campo-titulo" class="form-control" required="required"
                                           placeholder="Título" autofocus="autofocus" name="titulo" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-descricao">Descrição</label>
                                    <textarea cols="25" rows="3" id="campo-descricao" class="form-control" placeholder="Descrição"
                                              required="required" autofocus="autofocus" name="descricao"></textarea>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-duracao">Duração</label>
                                    <input type="datetime" id="campo-duracao" class="form-control tempo" placeholder="Duração"
                                           required="required" autofocus="autofocus" name="duracao" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success col-md-12" type="submit">Registrar</button>
            </form>
            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Index", "Tarefa")">Deseja alterar alguma tarefa já cadastrada ?</a>
            </div>
        </div>
    </div>
</div>

Views/Views/Tarefa/Editar.cshtml
@{
    ViewBag.Title = "Editar";
}

<div class="container">
    <div class="card card-register mx-auto mt-4">
        <div class="card-header">Editar Tarefa</div>
        <div class="card-body">
            <form action="@Url.Action("Update")" method="post">
                <input type="hidden" name="id" value="@ViewBag.Tarefa.Id" />
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-12">
                            <div class="form-label-group">
                                <label for="id">Código</label>
                                <input type="text" id="id" name="id" class="form-control"
                                       placeholder="Código" required="required"
                                       value="@ViewBag.Tarefa.Id" readonly="readonly" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-usuario">Usuario</label>
                                    <select id="campo-usuario" name="idUsuarioResponsavel" class="form-control" required="required">
                                        @foreach (Model.Usuario usuario in ViewBag.Usuarios)
                                        {
                                            if (usuario.Id == ViewBag.Tarefa.IdUsuarioResponsavel)
                                            {
                                                <option value="@usuario.Id" selected="selected">@usuario.Nome</option>
                                            }
                                            else
                                            {
                                                <option value="@usuario.Id">@usuario.Nome</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <label for="campo-projeto">Projeto</label>
                                    <select id="campo-projeto" name="idProjeto" class="form-control" required="required">
                                        @foreach (Model.Projeto projeto in ViewBag.Projetos)
                                        {
                                            if (projeto.Id == ViewBag.Tarefa.IdProjeto)
                                            {
                                                <option value="@projeto.Id" selected="selected">@projeto.Nome</option>
                                            }
                                            else
                                            {
                                                <option value="@projeto.Id">@projeto.Nome</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-label-group">
                                        <label for="campo-categoria">Categoria</label>
                                        <select id="campo-categoria" name="idCategoria" class="form-control" required="required">
                                            @foreach (Model.Categoria categoria in ViewBag.Categorias)
                                            {
                                                if (categoria.Id == ViewBag.Tarefa.IdCategoria)
                                                {
                                                    <option value="@categoria.Id" selected="selected">@categoria.Nome</option>
                                                }
                                                else
                                                {
                                                    <option value="@categoria.Id">@categoria.Nome</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-label-group">
                                        <label for="campo-titulo">Título</label>
                                        <input type="text" id="campo-titulo" class="form-control" required="required"
                                               placeholder="Título" autofocus="autofocus" name="titulo" value="@ViewBag.Tarefa.Titulo" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-label-group">
                                        <label for="campo-descricao">Descrição</label>
                                        <textarea cols="25" rows="3" id="campo-descricao" class="form-control" placeholder="Descrição"
                                                  required="required" autofocus="autofocus" name="descricao">@ViewBag.Tarefa.Descricao</textarea>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-label-group">
                                        <label for="campo-duracao">Duração</label>
                                        <input type="datetime" id="campo-duracao" class="form-control tempo" placeholder="Duração"
                                               required="required" autofocus="autofocus" name="duracao" value="@ViewBag.Tarefa.Duracao.ToString("HH:mm:ss")" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-success col-md-12" type="submit">Salvar</button>
</form>
            <div class="text-center">
                <a class="d-block small mt-3" href="@Url.Action("Index", "Tarefa")">Deseja alterar alguma tarefa já registrada ?</a>
            </div>
        </div>
    </div>
</div>

Views/Views/Tarefa/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Lista de Tarefas</h2>
<div>
    <a href="@Url.Action("Cadastro")" class="btn btn-primary mt-1">Nova Tarefa</a>
</div>
<div class="row">
    <div class="col-3 offset-9">
        <div class="form-group">
            <input type="text" id="campo-pesquisa" placeholder="Busca" class="form-control" />
        </div>
    </div>
</div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Código</th>
            <th>Responsável</th>
            <th>Projeto</th>
            <th>Categoria</th>
            <th>Título</th>
            <th>Descrição</th>
            <th>Duração</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody id="lista-tarefas"></tbody>
    <tfoot>
        <tr>
            <th>Código</th>
            <th>Responsável</th>
            <th>Projeto</th>
            <th>Categoria</th>
            <th>Título</th>
            <th>Descrição</th>
            <th>Duração</th>
            <th>Ação</th>
        </tr>
    </tfoot>
</table>
<script src="~/Scripts/Tarefas/Tarefa.js"></script>   